### PR TITLE
Adding CHIRPS analysis at district level

### PR DESCRIPTION
**Pull request by PaulineNimo**

### CODE REVIEW

**Review by caldwellst — CHANGES_REQUESTED** [review]
Hi Pauline! Nice stuff! Overall the analysis looks good. However, I think we should break this up into:

1st script: `01_...R` processes the CHIRPS data for Somalia and saves out it (as you've done). Don't comment this work out and just leave it as a standalone script.

2nd script: Incorporate that CSV into the overall data frame that I've produced int he original `01_...R`, so that we can have all data together.

3rd script: Plotting scripts that you've put together.

This way we separate out the analysis and data wrangling and plotting.

**Comment by PaulineNimo** [comment]
> Hi Pauline! Nice stuff! Overall the analysis looks good. However, I think we should break this up into:
> 
> 1st script: `01_...R` processes the CHIRPS data for Somalia and saves out it (as you've done). Don't comment this work out and just leave it as a standalone script.
> 
> 2nd script: Incorporate that CSV into the overall data frame that I've produced int he original `01_...R`, so that we can have all data together.
> 
> 3rd script: Plotting scripts that you've put together.
> 
> This way we separate out the analysis and data wrangling and plotting.

Thanks @caldwellst. Will make the changes. To clarify, are you recommending having 03_...R, 04_...R and 05_...R separate files for the various reading, analysis and plotting scripts? If so, we may need to rename the 01_ and 02_ files in the main branch.

**Comment by caldwellst** [comment]
Yeah exactly! I think renaming them is perfect. We can just have the first one process your CHIRps data, the second generating the full data, the third plotting the scripts. Although if we wanted separate scripts for each data source maybe we do that too? Whatever you think is best!

**Comment by caldwellst** [comment]
Hi @PaulineNimo, how's this coming along?

**Comment by PaulineNimo** [comment]
Hi @caldwellst, the code should be in 3 separate scripts now with each step saved to the folder on Drive. 

I also initiated a README since the rhdx and idmc packages used in the wrangle data script do not appear to be on CRAN and might be useful to instruct on how to install them.

**Pull request merged**
